name: Update Daily Paper

on:
  label:
    types:
      - created
  schedule:
    - cron: '30 16 * * 0-4'

permissions:
  contents: write
  issues: write

jobs:
  update_daily_papers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update papers
        run: |
          python main.py

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Ensure commits and rebase onto origin/master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # add and commit generated files (adjust paths as needed)
          git add README.md .github/ISSUE_TEMPLATE.md || true
          # if there are no changes, exit gracefully
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "✏️ Update papers automatically." || { echo "commit failed"; exit 1; }

          # fetch latest remote master and rebase our commit(s) onto it
          git fetch origin master --prune
          # try to rebase; if conflict, abort and fail workflow so you can inspect
          if ! git rebase origin/master; then
            echo "Rebase conflict, aborting. Review manually."
            git rebase --abort
            exit 1
          fi

      - name: Push changes (safe)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 默认安全推送（fast-forward 或 rebase 后的推送）
          git push --follow-tags origin master
