name: Update

on:
  label:
    types:
      - created # for test
  schedule:
      - cron: '30 16 * * 0-4' # 00:30 Beijing time every Monday to Friday

permissions:
  contents: write
  issues: write 

jobs:
  update_daily_papers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Fetch remote and rebase onto origin/master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 确保 origin 使用 token（checkout 通常已经配置好凭据）
        # 拉取远端最新 master，然后把本地更改 rebase 到远端之上
        git fetch origin master --prune
        git rebase origin/master

    - name: Update papers
      run: |
        python main.py

    - name: Commit and push changes
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: '✏️ Update papers automatically.'
        force-add: 'true'
        files: README.md .github/ISSUE_TEMPLATE.md
        name: github-actions[bot]
        force-push: 'true'

    - name: Create an issue to notify
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
